name: GDBKokkos
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.35.1
  - binutils_linux-64=2.35
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cmake=3.20.2
  - expat=2.4.1
  - gcc_impl_linux-64=9.3.0
  - gcc_linux-64=9.3.0
  - gdb=9.2
  - gxx_impl_linux-64=9.3.0
  - gxx_linux-64=9.3.0
  - kernel-headers_linux-64=2.6.32
  - krb5=1.19.1
  - ld_impl_linux-64=2.35.1
  - libcurl=7.76.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-devel_linux-64=9.3.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - libnghttp2=1.43.0
  - libssh2=1.9.0
  - libstdcxx-devel_linux-64=9.3.0
  - libstdcxx-ng=9.3.0
  - libuv=1.41.0
  - lz4-c=1.9.3
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.1.2
  - python=3.8.10
  - python_abi=3.8
  - readline=8.1
  - rhash=1.4.1
  - setuptools=49.6.0
  - six=1.16.0
  - sqlite=3.35.5
  - sysroot_linux-64=2.12
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
