name: Set up Conda to test and release to PyPi
on: [push, pull_request]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: GDBKokkos
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: install
        shell: bash -l {0}
        run: |
            python -m pip install --upgrade pip
            python -m pip install -q '.[tests]'
      - name: Run pytest
        shell: bash -l {0}
        run: |
            pytest
